### ISSUE TITLE
Maven version of this project

### ISSUE THREAD

**Issue by shah-smit** [Apress/pivotal-certified-pro-spring-dev-exam-02#11]

**Comment by iuliana** [comment]
Hello @shah-smit, 

I will do a maven version for the 3rd revision of the book since so many people have asked.  :)

Cheers!

**Comment by houssemzaier** [comment]
I 'm an android guy that is trying to do some personal web apps using kotlin and the most powerfull Java framework
I think that the Gradle is the best choice.
No xml and no overhead. 
All the serious companies did the migration to that build tool.

When do you think that the 3rd version will he released @iuliana ? 
By the way I hope  it will it be in Kotlin - coroutines 100%  for a modern and reactive approach.

Many thanks you for this easy readable book  !

**Comment by iuliana** [comment]
Hello @houssemzaier, 

Thank you for buying my book and thank you for the feedback!

I like Kotlin a lot as well. Unfortunately this book is a study guide for Java Spring Certification and the only way there will be more Kotlin in it is if VMware decides to make a Kotlin Spring certification. 

The 3rd edition will probably be available at the end of 2021, when Spring 6 is released.

Cheers, 
Iuliana Cosmina

**Comment by geffchang** [comment]
I have the book and would appreciate a Maven version. As it currently stands, I need to take a quick course on Udemy, but Maven would  still be appreciated. :)
