### ISSUE TITLE
Figure 2.3 is not clear on PDF version

### ISSUE THREAD

**Issue by davidbanhos** [Apress/pivotal-certified-pro-spring-dev-exam-02#17]
First, thank you @iuliana for this nice material. It's indeed very well written, congrats!

Well, I'm not sure if I could open this type of PDF formatting issue here, but there's it is.

The Figure 2.3 is not clear at all at PDF version, please follow the sample attached.

![BookFig2_3](https://user-images.githubusercontent.com/460673/93726123-782e1000-fbf7-11ea-9f90-34e34e4980a0.png)

I'm not sure if that is related to the figure processing, or due to the PDF formatter. The EPUB version is a bit more crispy. 

Regards.

**Comment by iuliana** [comment]
Hello David, 

Interesting, I will try to fix this it in the next edition. I think the image is not suitable for a book format anyway. 
Oh well, you live, you learn.  :)
Until then, here's the image: [Image 2.3](https://iulianacosmina.com/wp-content/uploads/2020/09/9781484208121_Figure_02-03.png)

Cheers, 
Iuliana
