### ISSUE TITLE
Unable to run unit test

### ISSUE THREAD

**Issue by pascalito007** [Apress/pivotal-certified-pro-spring-dev-exam-02#8]
Hi,
I have issue running unit test. How to fixe this please ?
Please take a look at screenshot.
I test it using java 8 and java 13 but having same issue.

<img width="862" alt="Capture d’écran 2020-03-21 à 10 40 01" src="https://user-images.githubusercontent.com/4120406/77223833-5d9faf00-6b60-11ea-8a37-e8c92fc38676.png">

**Comment by iuliana** [comment]
Hello, 

The the --module-path is the analogous of --classpath for modules. Is only used in JDK 9+.
Check your system settings. It appears the default JDK is not JDK 13. 

Cheers, 
Iuliana
